/*
 * CINELERRA
 * Copyright (C) 2016-2020 William Morrow
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published
 * by the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * General Public License for more details.
 *
 * You should have received a copy of the GNU General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307
 * USA
 */

#ifndef _DBWINDOW_INC_
#define _DBWINDOW_INC_

class DbSearchItem;
class DbWindow;
class DbWindowGUI;
class DbWindowInfoText;
class DbWindowTitleText;
class DbWindowMatchCase;
class DbWindowText;
class DbWindowStart;
class DbWindowDeleteItems;
class DbWindowCancel;
class DbWindowList;
class DbWindowCanvas;
class DbWindowVIcon;
class DbWindowVIconThread;
class DbWindowItem;
class DbWindowScan;

#endif
